### ISSUE TITLE
Support for Visual Studio 2012

### ISSUE THREAD

**Issue by JPomichael** [wakatime/visualstudio-wakatime#1]
Not found wakatime in Visual Studio 2012(simplified Chinese) Extensions and Updates

![20150109173002](https://cloud.githubusercontent.com/assets/1901960/5677762/8714ccc6-9825-11e4-82e6-5e34c59c7f26.png)

**Comment by alanhamlett** [comment]
Thanks, I'll look into it.

**Comment by jonatasfreitasv** [comment]
+1

**Comment by MitjaBezensek** [comment]
+1

**Comment by alanhamlett** [comment]
That's because only Visual Studio 2013 is supported so far:
https://visualstudiogallery.msdn.microsoft.com/ca0ea1f3-e824-4586-a73e-c8e4a65323d8

Still working on support for 2010 and 2015.

**Comment by alanhamlett** [comment]
Added support for VS 2012 with #12

**Comment by JPomichael** [comment]
Thanks. I can use it now
