### ISSUE TITLE
Migration required to VS 2013

### ISSUE THREAD

**Issue by gandarez** [wakatime/visualstudio-wakatime#10]
Hi all!

Just forked and trying to open it in my Visual Studio 2013 Premium got an error as below.
![error_1](https://cloud.githubusercontent.com/assets/782854/7619476/5079cf1a-f98f-11e4-9282-e8de126723ab.png)
![error_2](https://cloud.githubusercontent.com/assets/782854/7619478/52abadc6-f98f-11e4-9b07-8ab43f7fa3d0.png)

**Comment by alanhamlett** [comment]
It opens for me in Visual Studio 2013 Community. This error is usually fixed by editing the .csproj file and changing the `MinimumVisualStudioVersion` or `VisualStudioVersion` versions to match your IDE version.

**Comment by gandarez** [comment]
Hi @alanhamlett.
I figured out that VS 2013 needs its SDK to open this project. From my forked project, which I'll try to fix a bug encountered, I'll also change Readme to include a pre-requisite section.

**Comment by alanhamlett** [comment]
Oh yea forgot about needing the SDK installed. What other bug did you encounter?

**Comment by gandarez** [comment]
I changed Readme.md into the pull request https://github.com/wakatime/visualstudio-wakatime/pull/11
