### ISSUE TITLE
Not gathering data after having downloaded

### ISSUE THREAD

**Issue by shrike99** [wakatime/visualstudio-wakatime#103]
I have downloaded WakaTime on both Visual Studio and Visual Studio Code. When I run it on Visual Studio Code, it loads up perfectly on my dashboard with all my data showing and doing all the correct things, but when I use my Visual Studio, nothing shows up. I have looked at the Output window and here is what it shows:

`[WakaTime Debug 05:25:02 PM] ["C:\Python30\pythonw", "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\cli.py", "--key", "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX2384", "--entity", "C:\Users\User-PC\source\repos\WpfApp1\WpfApp1\MainWindow.xaml.cs", "--time", "1591201500.137817", "--plugin", "visualstudio/16.0 visualstudio-wakatime/10.0.3", "--write", "--project", "WpfApp1", "--extra-heartbeats"]
[WakaTime Debug 05:25:02 PM] Traceback (most recent call last):  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\projects\subversion.py", line 20, in <module>    from collections import OrderedDictImportError: cannot import name OrderedDictDuring handling of the above exception, another exception occurred:Traceback (most recent call last):  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\cli.py", line 24, in <module>    import wakatime  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\__init__.py", line 17, in <module>    from .main import execute  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\main.py", line 32, in <module>    from .api import send_heartbeats, get_time_today  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\api.py", line 21, in <module>    from .offlinequeue import Queue  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\offlinequeue.py", line 19, in <module>    from .heartbeat import Heartbeat  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\heartbeat.py", line 17, in <module>    from .project import get_project_info  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\project.py", line 21, in <module>    from .projects.subversion import Subversion  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\projects\subversion.py", line 22, in <module>    from ..packages.ordereddict import OrderedDict  # pragma: nocover  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\packages\ordereddict.py", line 23, in <module>    from UserDict import DictMixinImportError: No module named UserDictDuring handling of the above exception, another exception occurred:Traceback (most recent call last):  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\projects\subversion.py", line 20, in <module>    from collections import OrderedDictImportError: cannot import name OrderedDictDuring handling of the above exception, another exception occurred:Traceback (most recent call last):  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\cli.py", line 31, in <module>    import wakatime  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\__init__.py", line 17, in <module>    from .main import execute  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\main.py", line 32, in <module>    from .api import send_heartbeats, get_time_today  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\api.py", line 21, in <module>    from .offlinequeue import Queue  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\offlinequeue.py", line 19, in <module>    from .heartbeat import Heartbeat  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\heartbeat.py", line 17, in <module>    from .project import get_project_info  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\project.py", line 21, in <module>    from .projects.subversion import Subversion  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\projects\subversion.py", line 22, in <module>    from ..packages.ordereddict import OrderedDict  # pragma: nocover  File "C:\Users\User-PC\AppData\Roaming\WakaTime\wakatime-master\wakatime\packages\ordereddict.py", line 23, in <module>    from UserDict import DictMixinImportError: No module named UserDict` 

But I can't understand why it's not working. Any help?

**Comment by gandarez** [comment]
We updated to new `wakatime-cli` go based. Please update your extension and retry.
