### ISSUE TITLE
Measure debugging time

### ISSUE THREAD

**Issue by MattLebrao** [wakatime/visualstudio-wakatime#106]
Considering wakatime APIs imply the system is ready to time activities other than coding, it would be really useful if we could also measure the time we spend debugging projects. Debugging is as much part of the development time as coding itself.

**Comment by alanhamlett** [comment]
We just need to find the IDE event for debugging and listen to it:
https://github.com/wakatime/visualstudio-wakatime/blob/69f0ab132580a7caa3587e8c2b90052b42883a70/WakaTime/WakaTimePackage.cs#L106

**Comment by MattLebrao** [comment]
Thank you for pointing out this document. I've already found the relevant VSIX documentation on the DebuggerEvents class. I'm forking the repo and maybe I'll make a pull request when it's properly done and tested.

**Comment by MattLebrao** [comment]
Thank you for pointing out this document. I've already found the relevant VSIX documentation on the DebuggerEvents class. I'm forking the repo and maybe I'll make a pull request when it's properly done and tested.

**Comment by MattLebrao** [comment]
@alanhamlett I've had to make changes to another repo ("wakatime/nuget-wakatime-shared-extension-utils") in order to have the standard `WakaTime` class (referenced by the VS Plugin) to support the cli's "category" parameter. Later on I'm gonna need some info on how to proceed with the pull requests considering I've had to change two separate repos. It would make sense to pull the dependency first, and the dependant second, but it would be nice to hear from someone from WakaTime about best practices or maybe an exceptional procedure.

**Comment by alanhamlett** [comment]
First the Nuget package should be updated, then we can merge the PR for VS.

**Comment by gandarez** [comment]
@MattLebrao submit the PR and I take care of it.

**Comment by MattLebrao** [comment]
@gandarez I was actually writing a quick question here as you made your comment.
As expected I got carried away with the possibilities and implemented more things than I originally intended haha
I've implemented some new editor events I think may have been overlooked (or perhaps non-existent at the time the plugin was wrote). All I need now is some conceptual info. I am setting up how each event will setup a heartbeat as they call `HandleActivity`.
For instance, what is the entity-type "app" used for? I was thinking of using it, for example, when build start. It would queue a heartbeat with the "building" category, the project's output file full name as entity, and "app" as entity-type. What do you think? Or did I mis-interpret its usage?

**Comment by MattLebrao** [comment]
I've made quite a few changes I believe are gonna be welcome. Among them, I realized the plugin lacked a response to file changes, which meant a big potential for inaccuracies. Initially I thought it was intentional, until I saw the [Handling Editor Events](https://wakatime.com/help/creating-plugin#handling-editor-events) section of the "Creating a Plugin" help page. Which made me think it was probably due to the fact `DocumentEvents` does not expose such an event (and shouldn't either, as this is intended to respond to file manipulation events, which it does well).

An event for when a file is modified is exposed in the `TextEditorEvents` class. It gets fired "randomly" upon opening a project, or when while building but it's possible to filter out the "random" calls to only produce a heartbeat when an actual open file has been modified in the editor. I believe this will significantly improve accuracy, specially when the user have set smaller timeouts.
I initially thought this could overflow the heartbeat queue, then I realized the `HandleActivity` method has criteria for ignoring the same event happening in small intervals.

In fact, I was suspicious that when working on the same file for a long time without saving it, it created a gap in the activity timeline (even though there shouldn't be one), it was one of the things that led me to want to contribute. But I didn't realize until yesterday that the project was open source.

**P.S.: I'll be documenting *all* my changes on the PR.**

P.P.S.: Forgive me if I'm over-reporting (or just plain blabbing), or if the issue page isn't the proper place to do so. Although I've been coding for over a decade, this is actually my first time collaborating on GitHub. I've always been kind of a happy loner, but I'm loving this experience.

**Comment by gandarez** [comment]
> @gandarez I was actually writing a quick question here as you made your comment.
> As expected I got carried away with the possibilities and implemented more things than I originally intended haha
> I've implemented some new editor events I think may have been overlooked (or perhaps non-existent at the time the plugin was wrote). All I need now is some conceptual info. I am setting up how each event will setup a heartbeat as they call `HandleActivity`.
> For instance, what is the entity-type "app" used for? I was thinking of using it, for example, when build start. It would queue a heartbeat with the "building" category, the project's output file full name as entity, and "app" as entity-type. What do you think? Or did I mis-interpret its usage?

To understand all the differences and how to mix them up please refer to @alanhamlett he is the owner of that.

**Comment by alanhamlett** [comment]
> the project's output file full name as entity, and "app" as entity-type

We should copy Xcode and use `type: file` with `category: building`. The `app` type is a placeholder for [wakatime-desktop](https://github.com/wakatime/desktop) to track app window usage without needing an IDE plugin.

**Comment by alanhamlett** [comment]
> the project's output file full name as entity

This one depends: Can a file be edited at the same time as building in background? If so, we should use the currently focused code file and just change category to `building`. I can see cases where builds last several minutes and the dev is typing code while waiting. If building blocks all IDE usage, then it's ok to use the build output file.

**Comment by MattLebrao** [comment]
> We should copy Xcode and use `type: file` with `category: building`. The `app` type is a placeholder for [wakatime-desktop](https://github.com/wakatime/desktop) to track app window usage without needing an IDE plugin.

Roger that, @alanhamlett 

> This one depends: Can a file be edited at the same time as building in background? If so, we should use the currently focused code file and just change category to building. I can see cases where builds last several minutes and the dev is typing code while waiting. If building blocks all IDE usage, then it's ok to use the build output file.

I'll check whether or not the build process blocks the IDE, I think it does, but either way, the IDE saves all files at the beginning of a build and uses that version on the build, which means **changes during the code will be additions not included in the ongoing build**, and therefore will be considered "coding" by the DocumentOpened, DocumentSaved, and the newly implemented LineChanged events. When they fire, these events will still use the proper document name as entity (since all three events pass in parameters specifying the file, which means it doesn't matter if the build process changes the current "ActiveDocument" property). **Think of it as coding a file whilst building a different file** and having WakaTime measure both concurrent activities. Then again, if I understand it correctly, it doesn't make sense to use the "building" category for source code files, when the file being built by the process is the project's output.


**Now for the debugging category:**
The DocumentOpened, DocumentSaved and LineChanged events will use the "debugging" category for the active document upon changes if the debugger is in BreakMode, which means the project is being debugged and the the changes are being made while debugging is stopped at a breakpoint/exception. To my understanding that truly means the debugging of that specific source code file, while the DebuggerOnEnterRunMode event (when debug starts, or continues execution after leaving break mode), the DebuggerOnEnterDesignMode event (when debug ends for any reason) and the DebuggerOnEnterBreakMode event (upon hitting a breakpoint or stepping trough code) will all create the same heartbeat setup: project output file as entity, "debugging" as category. This will not prevent file changes to be properly recorded with the correct document as entity.

The idea here is that while debugging your application, the text editor and file manager will both continue to report the debugging of source code files in case they change in anyway (with the proper files as entities) WHILE the debugger will report the debugging of the project output. **The result is that we will simultaneously record debugging times for source files and the project output itself.**

We MUST use the project's output file for these events because we don't want to use the process name, which could be another unrelated application used to debug a class library, or even a VS instance used to debug a VSIX project. (Makes no sense to record time debugging "devenv.exe" which isn't even part of the project and whose path isn't rooted on the project's root.

With the debugger events reporting the debugging of the project as a whole in three different events, I believe we have achieved sufficient heartbeat recurrence to accurately measure the debugging time of an application, without sacrificing the measurement of the modifications made to the files while debugging (in fact, the latter will remains the same, only reporting "debugging" instead of "codding" while the debugger is in breakmode).

**Debugger in Run mode**
While the debugger is in run mode, it means the debugging process is running and VS is attached to it, but the user isn't accompanying the execution flow. More often than not (at least with most devs I know) this means the dev is no longer debugging the source files and has rather moved on with the coding, but either didn't notice, or didn't want to stop the process to test timely situations. Their changes will not be applied to the current debugging session and therefore, this activity is considered "coding" of the source code files (not "debugging" anymore) while simultaneously "debugging" of the project output (which is still attached and running).

Explaining it this way makes it sound a lot more complicated than it actually is. My changes are actually very simple hahaha (and I followed the practices already present at the project, so it will be a piece of cake to get them, even though reading someone else's code is usually a form of torture (according to a previous SO's survey hahah)).

I'll properly document everything in the plugin's pull request. I can see this text is far from well-redacted or clear enough, but I have been up since I got your (@alanhamlett ) first reply on the issue yesterday 23h ago. Thanks to coffee my coding marches on as strong as ever, but my text production skills have suffered hahaha

P.S.: This was my first issue and I apologize for breaking best practices and discussing code review here. I just now learnt I could have made a draft pull request from the beginning so you guys could follow my work (instead of waiting until I am absolutely ready to pull to open the request).

Again, I'm a git noob, forgive me.

**Comment by MattLebrao** [comment]
As I was documenting my changes on the pull request I had an idea that will improve the measuring of long build times (and THEN I understood what @alanhamlett meant with:
> I can see cases where builds last several minutes and the dev is typing code while waiting.

Basically, the file related events will keep track of the build status (they already keep track of the debugger to act on it). If there is an ongoing build it will act upon it.
Like I said, it doesn't make much sense to record "building" activity on source code files, since you don't build a single file, but the project. So when there is a build occurring, file change related events will call HandleActivity twice. One for the actual file being worked on with the "coding" activity, and once for the project's output file with the building activity. This way the two actions, which are separate and should be measures separately, will in fact will be.

(I'm starting to feel like I spend more time reporting than actually coding, the time it took for me to write this I could have done the changes twice or thrice haha)
