### ISSUE TITLE
Display worked time in status bar

### ISSUE THREAD

**Issue by guibranco** [wakatime/visualstudio-wakatime#108]
Display the worked time on project in the Visual Studio status bar, like the Visual Studio Code extension.

![image](https://user-images.githubusercontent.com/3362854/92309039-55a1c300-ef78-11ea-9be7-9a00a18b4dec.png)

**Comment by gandarez** [comment]
Working in a possible solution.

**Comment by guibranco** [comment]
@gandarez hello, any update on this ?

**Comment by zhangqi0131** [comment]
Looking forward to it...

**Comment by JasonWei512** [comment]
The problem is, Visual Studio doesn't provide a UI extension point for status bar like VSCode.
You can only display text in the left corner of status bar, which can be overridden by other extensions.

https://stackoverflow.com/questions/72931459/visual-studio-extension-add-button-to-editors-status-bar

**Comment by guibranco** [comment]
@JasonWei512 ReSharper add some icons and text to status bar, do you know how they archive that ?
![image](https://user-images.githubusercontent.com/3362854/235157011-cc1175d1-5f62-45a1-94ff-abaa34214f9b.png)

**Comment by JasonWei512** [comment]
@guibranco 
I have no idea. Seems it's not documented anywhere.
Maybe @madskristensen knows.

**Comment by madskristensen** [comment]
See this: https://github.com/madskristensen/ShowTheShortcut/blob/master/src/StatusbarInjector.cs

**Comment by JasonWei512** [comment]
@madskristensen Thanks a lot! It works!

![image](https://user-images.githubusercontent.com/16899918/235281476-c9118774-4705-44fc-9609-189f6215b4a6.png)

``` csharp
global using Community.VisualStudio.Toolkit;
global using Microsoft.VisualStudio.Shell;
global using System;
global using Task = System.Threading.Tasks.Task;
using System.Runtime.InteropServices;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace VSIXProject
{
    [PackageRegistration(UseManagedResourcesOnly = true, AllowsBackgroundLoading = true)]
    [InstalledProductRegistration(Vsix.Name, Vsix.Description, Vsix.Version)]
    [ProvideMenuResource("Menus.ctmenu", 1)]
    [Guid(PackageGuids.VSIXProjectString)]
    public sealed class VSIXProjectPackage : ToolkitPackage
    {
        protected override async Task InitializeAsync(CancellationToken cancellationToken, IProgress<ServiceProgressData> progress)
        {
            await this.RegisterCommandsAsync();

            TextBlock textBlock = new()
            {
                Text = "🕑 31 mins",
                Foreground = new SolidColorBrush(Colors.White),
                VerticalAlignment = VerticalAlignment.Center,
                Margin = new Thickness(6, 0, 6, 0)
            };

            await StatusBarInjector.InjectControlAsync(textBlock);
        }
    }
}
```

**Comment by JasonWei512** [comment]
Here's a working build for Visual Studio 2022:
[WakaTime.Dev17.zip](https://github.com/wakatime/visualstudio-wakatime/files/11442177/WakaTime.Dev17.zip)

My fork:
- https://github.com/JasonWei512/nuget-wakatime-shared-extension-utils
- https://github.com/JasonWei512/visualstudio-wakatime

![image](https://github.com/wakatime/visualstudio-wakatime/assets/16899918/4afba4f7-1a22-4fc7-9b56-a6372cba8b1b)

![image](https://github.com/wakatime/visualstudio-wakatime/assets/16899918/4800c69e-e3d1-406c-8bb3-fd74ba244db8)

**Comment by zhangqi0131** [comment]
I have installed Dev17，but today's coding time is always 0 secs.  And when I click Tools - WakaTime - Settings, the vs window will be unresponsive.
![image](https://github.com/wakatime/visualstudio-wakatime/assets/77319544/194bbb3f-a08c-4d23-abbe-b87acb91edc2)

**Comment by guibranco** [comment]
Very nice @JasonWei512, congrats on that work bro!

**Comment by gandarez** [comment]
Hi @JasonWei512 would you mind creating a PR for visual studio as well?

**Comment by JasonWei512** [comment]
@gandarez 
Here:
https://github.com/wakatime/visualstudio-wakatime/pull/144

**Comment by guibranco** [comment]
Any new about when this will be released and available in VS ?

**Comment by guibranco** [comment]
@JasonWei512 the PR shows the total worked on a given day, not on the specific project, right?

**Comment by alanhamlett** [comment]
> @JasonWei512 the PR shows the total worked on a given day, not on the specific project, right?

Right.



> Any news about when this will be released and available in VS ?

A new version was just released today.
