### ISSUE TITLE
Does not work on VS 2015

### ISSUE THREAD

**Issue by mmaenz** [wakatime/visualstudio-wakatime#109]
Installing is okay, after restart it fails.

Reason:
`<entry>
    <record>441</record>
    <time>2020/10/10 07:46:32.087</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [WakaTimePackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.Framework, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. Das System kann die angegebene Datei nicht finden.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.Framework, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. Das System kann die angegebene Datei nicht finden.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Shell.Framework, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)&#x000D;&#x000A;   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)&#x000D;&#x000A;   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly&amp; lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType&amp; attributeType, IRuntimeMethodInfo&amp; ctor, Boolean&amp; ctorHasParameters, Boolean&amp; isVarArg)&#x000D;&#x000A;   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)&#x000D;&#x000A;   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)&#x000D;&#x000A;   at System.RuntimeType.GetCustomAttributes(Type attributeType, Boolean inherit)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.RegisterToolboxItemDiscoveryFactories()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Initialize()&#x000D;&#x000A;   at WakaTime.WakaTimePackage.Initialize()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Protokollierung der Assemblybindung ist AUS.&#x000D;&#x000A;Sie k&#x00F6;nnen die Protokollierung der Assemblybindungsfehler aktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) auf 1 festlegen.&#x000D;&#x000A;Hinweis: Die Protokollierung der Assemblybindungsfehler f&#x00FC;hrt zu einer gewissen Leistungseinbu&#x00DF;e.&#x000D;&#x000A;Sie k&#x00F6;nnen dieses Feature deaktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] entfernen.&#x000D;&#x000A;</description>
    <guid>{52D9C3FF-C893-408E-95E4-D7484EC7FA47}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>`

The reason is the missing **Microsoft.VisualStudio.Shell.Framework, Version=15.0.0.0**.

Pulled source from github and wanted to edit that dependency but isn't possible:
![image](https://user-images.githubusercontent.com/22559887/95649716-2afadb00-0adf-11eb-896f-8560786db11e.png)

On releases and at the wakatime homepage it clearly says it is compatible with 2011-2019! It isn't.

Please repair. Or make it usable with older versions. Thank you.

**Comment by gandarez** [comment]
Which VS 2015 version are you using?

**Comment by mmaenz** [comment]
Thank you for helping me!

![image](https://user-images.githubusercontent.com/22559887/96239339-dd2f1880-0f9f-11eb-9f2d-0bafca44bccf.png)

**Comment by nvisage-gf** [comment]
Same issue with `Microsoft.VisualStudio.Shell.Framework, Version=15.0.0.0` not being located, same VS 2015 Professional Version 14.0.25431.01 Update 3; WakTime 1.0

**Comment by ClearSeve** [comment]
same

**Comment by ClearSeve** [comment]
![Uploading image.png…]()

**Comment by ClearSeve** [comment]
![image](https://user-images.githubusercontent.com/26833671/101706823-e7175880-3ac4-11eb-9fb6-91b3c9d41fca.png)

**Comment by SUXUMI** [comment]
The same issue:

![image](https://user-images.githubusercontent.com/5499359/114624687-1ed81c00-9cc2-11eb-8aad-de0bdc2b2b46.png)

![image](https://user-images.githubusercontent.com/5499359/114624460-c7d24700-9cc1-11eb-9c03-7d38c41a1106.png)

![image](https://user-images.githubusercontent.com/5499359/114624771-3e6f4480-9cc2-11eb-9890-451b048e30f4.png)

**Comment by xiaokangdream** [comment]
Same

**Comment by ClearSeve** [comment]
I need help

**Comment by ClearSeve** [comment]
WakaTime.log:

[Wakatime Info 09:34:57 AM] Initializing WakaTime v4.2.1
[Wakatime HandledException 09:34:57 AM] Are you behind a proxy? Try setting a proxy in WakaTime Settings with format https://user:pass@host:port. Exception Traceback:: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at WakaTime.Dependencies.DownloadAndInstallCli()
   at WakaTime.WakaTimePackage.InitializeAsync()
[Wakatime Info 09:34:57 AM] Finished initializing WakaTime v4.2.1

**Comment by gandarez** [comment]
We've just released a new version (`v11.0.0`), please update WakaTime and feel free to open a new issue.
