### ISSUE TITLE
Element not found Exception when installing

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/visualstudio-wakatime#112]
Error when installing on VS2019, originally reported [on twitter](https://twitter.com/xkem0x/status/1341752267603623936).

![vs2019_install_error](https://user-images.githubusercontent.com/522344/103025826-7120e180-4507-11eb-9d97-708fdb174c90.png)

**Comment by gandarez** [comment]
Released a new version (v11.0.0) might fix this issue.
