### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by pocki** [wakatime/visualstudio-wakatime#115]
Please add support for the new Visual Studio 2022.

**Comment by ReddeR1337** [comment]
any news ?

**Comment by alanhamlett** [comment]
Yes, we're almost ready with VS2022 support. [v11.0.0](https://github.com/wakatime/visualstudio-wakatime/releases/tag/11.0.0) just released is working towards that.

**Comment by gandarez** [comment]
Hi all,

WakaTime for VS 2022 is now available to be installed on VS 2022 preview.

https://marketplace.visualstudio.com/items?itemName=WakaTime.WakaTime-2022-preview
