### ISSUE TITLE
Wakatime not familiar with visual studio 2019 16.11

### ISSUE THREAD

**Issue by hootanht** [wakatime/visualstudio-wakatime#118]
wakatime Extention is crashing my visual studio version 16.11 (not responding) please fix that 
@alanhamlett

**Comment by gandarez** [comment]
Hi @hootanht,

Which WakaTime version have you installed? Also please take a look at `%AppData%\Microsoft\VisualStudio\<version>\ActivityLog.xml.` to find out some error.

**Comment by hootanht** [comment]
wakatime 11.00

**Comment by gandarez** [comment]
I have here the same VS 2019 update. Did you have a chance to take a look at log files?

**Comment by hootanht** [comment]
yeah, what should I do?
@gandarez

**Comment by gandarez** [comment]
`%AppData%\Microsoft\VisualStudio\<version>\ActivityLog.xml` any problem to any extension is printed in this file. Please take a look.

**Comment by hootanht** [comment]
https://user-images.githubusercontent.com/27281206/129407606-f5a4dcfc-8e44-4dfa-83fd-689694342641.mp4

@gandarez

**Comment by hootanht** [comment]
wakatime 10.3.1 is working fine but 11.00 is crashing all the time
@gandarez @alanhamlett

**Comment by hootanht** [comment]
![Screenshot 2021-08-14 120427](https://user-images.githubusercontent.com/27281206/129438880-6ea0e8b8-d57b-4392-938c-210d30c3985d.png)

**Comment by hootanht** [comment]
![Screenshot 2021-08-14 120543](https://user-images.githubusercontent.com/27281206/129438908-10900e49-54ca-4667-8611-6e8bb30d8ddb.png)

**Comment by gandarez** [comment]
Hi, without attaching `%AppData%\Microsoft\VisualStudio\<version>\ActivityLog.xml` won't be able to analyze the error.

**Comment by gandarez** [comment]
Hi @hootanht, a new version `v11.0.1` has been relesead. Please update and give me a feedback.

**Comment by hootanht** [comment]
@gandarez it's work fine now, thanks
