### ISSUE TITLE
Does not work with VS2015

### ISSUE THREAD

**Issue by zolakt** [wakatime/visualstudio-wakatime#125]
There has been a similar issue reported here https://github.com/wakatime/visualstudio-wakatime/issues/109

It is supposed to work with v11, but it doesn't, at least not for me.

It was working a while ago, it no longer does.
I've tried uninstalling/installing multiple times.
When I go to Tools->WakaTime->Settings it doesn't open any window.

In the ActivityLog.xml, I've found this:

`
CreateInstance failed for package [WakaTimePackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{52D9C3FF-C893-408E-95E4-D7484EC7FA47}
`

Is this really expected to work with VS2015, since it requires Microsoft.VisualStudio.Shell.15.0?
Isn't Microsoft.VisualStudio.Shell.15.0 a VS2017 package?

e.g. there is a similar discussion here about a different extension, with the same exception
https://stackoverflow.com/questions/46054343/visual-studio-2015-fail-to-load-package-because-microsoft-visualstudio-shell-15

It seems like it needs Microsoft.VisualStudio.Shell.14.0 in order to work for VS2015.

Is there a way to install an older version, which targets the older lib version?

**Comment by alanhamlett** [comment]
Yes, looks like when trying to support VS 2022 we had to upgrade to `Microsoft.VisualStudio.Shell.15.0` since VS 2022 won't work with `Microsoft.VisualStudio.Shell.14.0`.

> Is there a way to install an older version, which targets the older lib version?

Here's the list of older versions:
https://github.com/wakatime/visualstudio-wakatime/releases

@gandarez do you have any input on this?

**Comment by gandarez** [comment]
I'm still looking for a fix. First I need to confirm how's the lib is referenced and why this specific version is not working on 2015. I'll bring more details soon.

**Comment by alanhamlett** [comment]
@zolakt can you confirm which version of the plugin you have installed?

**Comment by zolakt** [comment]
I've just installed the latest from VS2015 (it doesn't let me choose a version). So it's 11.1.0

Can someone tell me what is the last version that references Microsoft.VisualStudio.Shell.14.0?
It 10.3.1 ok?

**Comment by zolakt** [comment]
10.0.3 seems fine, at first. The settings window in VS2015 is working again.

However, when I restart VS I get this error:
![image](https://user-images.githubusercontent.com/1048531/151512551-4117225b-4642-4789-b4da-2748cd08468a.png)

And in the ActivityLog.xml, it still seems something is requesting Microsoft.VisualStudio.Shell.15.0
![image](https://user-images.githubusercontent.com/1048531/151512689-cdd93331-ec5f-4fec-a634-450e7344b9da.png)

**Comment by zolakt** [comment]
10.0.3 seem to work, at first, but it's not sending any data.
The settings window is working again. Everything seems fine, but it doesn't send anything.
I've enabled debug. There is no .wakatime.log file in the user folder. Only .wakatime.cfg

Any suggestions?

**Comment by gandarez** [comment]
Please uninstall current extension and find for wakatime on the gallery to install a new version.

**Comment by ErivandoBR** [comment]
> Please uninstall current extension and find for wakatime on the gallery to install a new version.

I tested the new update (13.0.0) it is working in visual studio 2015 (and 2022), thanks.
