### ISSUE TITLE
Windows Defender warning (Win 11 VS 2022)

### ISSUE THREAD

**Issue by ADCJustinH** [wakatime/visualstudio-wakatime#128]
Using latest non preview versions of Windows 11 and Visual Studio 2022 I am getting constant warnings that 

PUA:Win32/Caypnamer.A!ml has been detected in wakatime-cli-windows-amd64.exe

**Comment by alanhamlett** [comment]
Tracking this in https://github.com/wakatime/wakatime-cli/issues/660

For now, please allow it to run since this is a false positive.
