### ISSUE TITLE
support for proxy using domain authentication

### ISSUE THREAD

**Issue by diegomesata** [wakatime/visualstudio-wakatime#13]
Hello, I'm behind firewall and visual studio is not uploading data to wakatime? 

Should I do any special configuration?

Thank you

**Comment by alanhamlett** [comment]
Sure, there is a proxy config in your `~/.wakatime.cfg` file:
https://github.com/wakatime/wakatime#configuring

**Comment by diegomesata** [comment]
My proxy uses domain authentication, I Set:

proxy = http://domain\user name:mypass@192.160.0.2:8085

But In the error log I got:

"ConnectionError": "HTTPSConnectionPool(host='wakatime.com', port=443): Max retries exceeded with url: /api/v1/heartbeats (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',)))"}}

**Comment by alanhamlett** [comment]
Can you try https instead of http in your proxy config? I'll make this default to https from now on, but this might work right now by just using https.

**Comment by diegomesata** [comment]
Hello, Alan thank you for your interest. I tested with https, but the error in the log is still the same

**Comment by alanhamlett** [comment]
Support for NTLM proxies was added with the wakatime cli release [v6.2.3](https://github.com/wakatime/wakatime/blob/master/HISTORY.rst#623-2017-02-15).
