### ISSUE TITLE
Cannot install plugin on Visual Studio 2022

### ISSUE THREAD

**Issue by notflask** [wakatime/visualstudio-wakatime#132]

**Comment by gandarez** [comment]
Hi @notflask please do provide more rich information rather than the title. Could you please follow our troubleshooting guide and paste here the logs you encounter?

https://github.com/wakatime/visualstudio-wakatime#troubleshooting

**Comment by notflask** [comment]
> Hi @notflask please do provide more rich information rather than the title. Could you please follow our troubleshooting guide and paste here the logs you encounter?
> 
> https://github.com/wakatime/visualstudio-wakatime#troubleshooting

![image](https://user-images.githubusercontent.com/78703851/180307068-839730c2-402e-48aa-9c3a-380b3d538fd1.png)
i'm just trying to install plugin from .vsix but i got an error

**Comment by notflask** [comment]
> Hi @notflask please do provide more rich information rather than the title. Could you please follow our troubleshooting guide and paste here the logs you encounter?
> 
> https://github.com/wakatime/visualstudio-wakatime#troubleshooting

tried to install from Extension > Manage Extensions > Online > Visual Studio Marketplace and it got installed, but why it won't install from .vsix file?
