### ISSUE TITLE
API key input cuts off full API key

### ISSUE THREAD

**Issue by Caeden117** [wakatime/visualstudio-wakatime#136]
Recently, WakaTime API keys have been prefixed with `waka_`. However, the Visual Studio plugin does not appear to account for this new prefix, as the last 5 characters of the full API key are cut when pasting directly from the WakaTime website. This results in an invalid API key, but can be worked around by copying the API key without the `waka_` prefix.

I am using WakaTime `13.0.0` with Visual Studio 2022.

**Comment by alanhamlett** [comment]
For now, remove the `waka_` prefix. We'll get this fixed soon.

**Comment by alanhamlett** [comment]
Fixed with 59e55f34f29b8051413312aa5d371fe9722f1bb3, but still need a release to the marketplace.

**Comment by Caeden117** [comment]
Thanks for the fast response and fix! Wasn't sure if this plugin was still being actively maintained.

**Comment by alanhamlett** [comment]
Version 13.0.1 released just now.

**Comment by alanhamlett** [comment]
@Caeden117 does it work for you now with the `waka_` prefix?

**Comment by gandarez** [comment]
Update it to `v13. 0.2`

**Comment by Caeden117** [comment]
@alanhamlett @gandarez Hey folks, installed WakaTime `13.0.2` on my laptop and the complete API key works just fine. Cheers!
