### ISSUE TITLE
WakaTime is not working on VS 2022 Professional and Community

### ISSUE THREAD

**Issue by michasacuer** [wakatime/visualstudio-wakatime#142]
As in topic description, I instralled WakaTime on two machines and its not working. 

How to pass ApiKey to WakaTime in Visual Studio 2022? After successfull installation nothing happened. Tried couple of times (installing and deinstalling) on two machines and nothing. Can you help me?

**Comment by michasacuer** [comment]
Side note: I am using JB Rider 2023 as well and no issue there, i passed api key and it is working

**Comment by alekami649** [comment]
I have issue like this, if click "Tools" -> "Wakatime" -> "Settings" Visual Studio just crashed.

**Comment by MagnetronDev** [comment]
I can also confirm on my machine that it is not working. I put in the correct API key and enabled debug mode. Everything in the Visual Studio Community output looks okay. There's a bunch of stuff reported in the log file and the cfg file looks correct too. However nothing is being reported in the dashboard at all. This is all with version 13.0.2 of the extension.

**Comment by alanhamlett** [comment]
@MagnetronDev that was a temporary issue with the dashboard today. The dashboard read incident is resolved now, things should be back to normal and all your code stats should be visible again.

**Comment by YatsukiRenka** [comment]
Same problem, I use both VSCode and VS2022 Enterprise, but this extention never works on VS2022, while works fine on VSCode.

**Comment by riccardomerlin** [comment]
I’m experiencing the same problem on Visual Studio 2022. Any updates on this, please?

**Comment by ALINGCAT** [comment]
Same problem. First time I got plugin. Popped up a dialog with an input for my api key. But not working. When I click the 'setting' menu item of wakatime, my VS will be blocked.

**Comment by gandarez** [comment]
Are you guys still experiecing this problem?

**Comment by gandarez** [comment]
I tested in VS 2022 Community please update to latest version `13.2.0`. Feel free to reopen this issue if it does not work.

**Comment by alanhamlett** [comment]
After updating the plugin is anyone still experiencing this problem?

**Comment by batreller** [comment]
I still have the same issue on visual studio 2022 17.14.6
