### ISSUE TITLE
WakaTime is not working on VS 2022 Professional 

### ISSUE THREAD

**Issue by qianyanglm** [wakatime/visualstudio-wakatime#143]
win10  This problem has a long time ,Please how much time does writer will solve this problem Please?

**Comment by alanhamlett** [comment]
Are you using this version of the extension?

https://marketplace.visualstudio.com/items?itemName=WakaTime.WakaTime-2022

**Comment by qianyanglm** [comment]
yes, it  is   13.0.2  .sometimes  it  works ,soemtimes  it doesnot work

**Comment by alanhamlett** [comment]
Can you try using a VPN when starting Visual Studio? It looks like a networking problem when the extension is trying to download wakatime-cli from GitHub.

**Comment by qianyanglm** [comment]
Thank you!!! I used VPN ,Now it works,thank you very much. I love it
