### ISSUE TITLE
Build failing in AppVeyor

### ISSUE THREAD

**Issue by guibranco** [wakatime/visualstudio-wakatime#145]
I am looking for the recently new version of this extension with the changes from #144 but I can not find that version, so I look at AppVeyor and the builds are failing from the last 2 years, is that correct ? 

Is this the issue, can I found the updated version somewhere else ? 

![image](https://github.com/wakatime/visualstudio-wakatime/assets/3362854/a543bf2a-a3b6-42b4-9f9d-ffa23b9262d5)

**Comment by JasonWei512** [comment]
Hi guibranco, the package below is compiled from https://github.com/wakatime/visualstudio-wakatime/commit/779e2e9a81c80b1177ebd6d2f65360996f6a4dd1:
[WakaTime-VisualStudio.zip](https://github.com/wakatime/visualstudio-wakatime/files/11928632/WakaTime-VisualStudio.zip)

**Comment by guibranco** [comment]
Thanks @JasonWei512

**Comment by alanhamlett** [comment]
We're working on switching to GitHub Actions for building all versions of this extension.
