### ISSUE TITLE
Locking file randomly

### ISSUE THREAD

**Issue by rolivares** [wakatime/visualstudio-wakatime#152]
Seem to the extension using VS and starting VS as ADMIN  randomly is locking files. So, suddenly changes maded into files could'n  been saved because some process is locking the file asking to save into alternative path.

Using Handle  (https://learn.microsoft.com/en-us/sysinternals/downloads/handle) I've found wakatime is locking the file.

Sadly, I can not write some stepts in order to repeat the lock, because seems to be randlomly or unknoun behavior.

**Comment by alanhamlett** [comment]
The file being locked is one opened by you inside Visual Studio? The plugin does read your opened files using wakatime-cli for things like total file length, and language detection. Maybe there's a way to read files without causing Windows to lock the file.

**Comment by alanhamlett** [comment]
Here's a [related thread](https://forum.syncthing.net/t/is-it-possible-for-syncthing-not-to-lock-files-in-windows-when-hashing-them/17086) pointing to [Go standard library code](https://github.com/golang/go/blob/8e658eee9c7a67a8a79a8308695920ac9917566c/src/syscall/syscall_windows.go#L366) showing `os.Open` uses non-exclusive mode. However, it does prevent the file from being renamed or deleted. We can write our own `syscall.Open` to bypass that, but it should already allow writing files while wakatime-cli is reading them.

**Comment by rolivares** [comment]
26.000 lines of code aprox
1MB size 
Test over 16:40 hrs on ClienteService.cs

Still blocking file .... It could be because the file size/length that init some not awaited response? On other files with "normal" size apparently it is not blocking ... 

![image](https://github.com/wakatime/visualstudio-wakatime/assets/348077/09dac1aa-d447-4738-ae86-57e9287e62d9)
[wakatime.log](https://github.com/wakatime/visualstudio-wakatime/files/13981025/wakatime.log)

**Comment by alanhamlett** [comment]
From your wakatime.log, you got the fixed version starting `2024-01-18T16:26:02-03:00`. Did the locking error happen after that time or only brefore?

**Comment by rolivares** [comment]
after and before , The fix didn't seems to work for this issue

**Comment by alanhamlett** [comment]
It only happens on files larger than 1MB? And it never happens with WakaTime disabled?

**Comment by alanhamlett** [comment]
I've looked through the [extension source code](https://github.com/wakatime/visualstudio-wakatime/blob/master/Dev17/WakaTimePackage.cs) and [WakaTime.Shared.ExtensionUtils source code](https://github.com/wakatime/nuget-wakatime-shared-extension-utils) to verify no extension code is opening or reading the currently focused file. It only uses the path as string, passing that to [wakatime-cli](https://github.com/wakatime/wakatime-cli).

If we can reproduce this, for example if it always happens using large files, then I'll re-open the issue.
