### ISSUE TITLE
[Discussion] Better way to get latest version of Wakatime cli

### ISSUE THREAD

**Issue by gandarez** [wakatime/visualstudio-wakatime#16]
Hi!

I think the better way for this plugin to know the latest version of wakatime client is through releases. Is it possible to besides adding into history file also create a new release at https://github.com/wakatime/wakatime/releases?
Since github has an api which retrieves all release information about a specific repository Wakatime plugin could be smarter.

**Comment by alanhamlett** [comment]
It's possible to create releases, but it won't change releasing to users. I still have to upload to https://visualstudiogallery.msdn.microsoft.com/ manually.

**Comment by gandarez** [comment]
I mean to create releases at wakatime python repository and then this plugin can connect and correctly get the latest version.

**Comment by alanhamlett** [comment]
That would introduce a dependency on [pip](https://github.com/pypa/pip) to install the pypi wakatime package. I think downloading from GitHub then unzipping is more reliable.

**Comment by gandarez** [comment]
The problem is the dependency of a constant string inside the plugin, it's not dynamic.

**Comment by alanhamlett** [comment]
Ok, we can use pypi to check the latest release version then download the zip from pypi and extract like we currently do.

**Comment by gandarez** [comment]
@alanhamlett the way of installing it seem to be good so far. What makes me thoughful is regarding the way of getting the latest version of wakatime python library. A static string pointing to a version which constantly changes could be a problem.

**Comment by gandarez** [comment]
Implemented in version 5.0.9
