### ISSUE TITLE
No Visual Studio Community/Express Support

### ISSUE THREAD

**Issue by benwoosley** [wakatime/visualstudio-wakatime#169]
As referenced in README, I'm unable to find an Express build profile (using VS2019). Additionally, I'm not able to see a difference in the "Express Release" and main release. Currently unable to get VS Community working because of this.

**Comment by gandarez** [comment]
Hi @benwoosley there's no Express edition for VS 2019, you should use Community edition with this [WakaTime version](https://marketplace.visualstudio.com/items?itemName=WakaTime.WakaTime).

**Comment by benwoosley** [comment]
I'm actually on VS2022, sorry for the confusion! i've tried installing this 
https://marketplace.visualstudio.com/items?itemName=WakaTime.WakaTime-2022

Screenshot of error:
<img width="433" alt="Screenshot 2024-02-05 at 2 25 24 PM" src="https://github.com/wakatime/visualstudio-wakatime/assets/56568238/011ce09c-31f0-4e53-90c4-6993e4c7ad71">


log : "Package Failed updates, dependency or conflict validations"

I'm running windows in Parallels on Mac M1, could be ARM issue?

**Comment by gandarez** [comment]
@benwoosley yes sure, we have a pending task to include building for ARM. The issue is tracked [here](https://github.com/wakatime/visualstudio-wakatime/issues/131).
