### ISSUE TITLE
Wakatime won't show up on marketplace in visual studio 2022 and won't install with the installation file

### ISSUE THREAD

**Issue by yaniraton** [wakatime/visualstudio-wakatime#175]
I have a M1 Pro MacBook Pro and I am using parallels to emulate arm 64 windows and I run visual studio 2022 there
When I tried to install Wakatime I could not find it on the marketplace and I tried using the installation file to install the extension outside the marketplace but the insulation file weren't work either

This is the installation logs
4/27/2024 3:22:30 PM - Microsoft VSIX Installer
4/27/2024 3:22:30 PM - -------------------------------------------
4/27/2024 3:22:30 PM - vsixinstaller.exe version:
4/27/2024 3:22:30 PM - 17.8.2365+1ea9c98024
4/27/2024 3:22:30 PM - -------------------------------------------
4/27/2024 3:22:30 PM - Command line parameters:
4/27/2024 3:22:30 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\magsimim\WakaTime.Dev16.vsix
4/27/2024 3:22:30 PM - -------------------------------------------
4/27/2024 3:22:30 PM - Microsoft VSIX Installer
4/27/2024 3:22:30 PM - -------------------------------------------
4/27/2024 3:22:32 PM - Initializing Install...
4/27/2024 3:22:32 PM - Searching for applicable products...
4/27/2024 3:22:33 PM - Found installed product - Visual Studio Community 2022
4/27/2024 3:22:33 PM - Found installed product - Global Location
4/27/2024 3:22:33 PM - Extension Details...
4/27/2024 3:22:33 PM - 	Identifier         : 52d9c3ff-c893-408e-95e4-d7484ec7fa47
4/27/2024 3:22:33 PM - 	Name               : WakaTime
4/27/2024 3:22:33 PM - 	Author             : WakaTime
4/27/2024 3:22:33 PM - 	Version            : 13.5.3
4/27/2024 3:22:33 PM - 	Description        : Metrics, insights, and time tracking automatically generated from your programming activity.
4/27/2024 3:22:33 PM - 	Locale             : en-US
4/27/2024 3:22:33 PM - 	MoreInfoURL        : https://github.com/wakatime/visualstudio-wakatime
4/27/2024 3:22:33 PM - 	InstalledByMSI     : False
4/27/2024 3:22:33 PM - 	SupportedFrameworkVersionRange : [4.8,)
4/27/2024 3:22:33 PM - 	SignatureState     : Unsigned
4/27/2024 3:22:33 PM - 	Supported Products : 
4/27/2024 3:22:33 PM - 		Microsoft.VisualStudio.Community
4/27/2024 3:22:33 PM - 			Version : [15.0,17.0)
4/27/2024 3:22:33 PM - 			ProductArchitecture : x86
4/27/2024 3:22:33 PM - 		Microsoft.VisualStudio.Pro
4/27/2024 3:22:33 PM - 			Version : [15.0,17.0)
4/27/2024 3:22:33 PM - 			ProductArchitecture : x86
4/27/2024 3:22:33 PM - 		Microsoft.VisualStudio.Enterprise
4/27/2024 3:22:33 PM - 			Version : [15.0,17.0)
4/27/2024 3:22:33 PM - 			ProductArchitecture : x86
4/27/2024 3:22:33 PM - 		Microsoft.VisualStudio.IntegratedShell
4/27/2024 3:22:33 PM - 			Version : [15.0,17.0)
4/27/2024 3:22:33 PM - 			ProductArchitecture : x86
4/27/2024 3:22:33 PM - 		Microsoft.VisualStudio.Ultimate
4/27/2024 3:22:33 PM - 			Version : [15.0,17.0)
4/27/2024 3:22:33 PM - 			ProductArchitecture : x86
4/27/2024 3:22:33 PM - 		Microsoft.VisualStudio.Premium
4/27/2024 3:22:33 PM - 			Version : [15.0,17.0)
4/27/2024 3:22:33 PM - 			ProductArchitecture : x86
4/27/2024 3:22:33 PM - 		Microsoft.VisualStudio.VSLS
4/27/2024 3:22:33 PM - 			Version : [15.0,17.0)
4/27/2024 3:22:33 PM - 			ProductArchitecture : x86
4/27/2024 3:22:33 PM - 	References         : 
4/27/2024 3:22:33 PM - 		-------------------------------------------------------
4/27/2024 3:22:33 PM - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
4/27/2024 3:22:33 PM - 		Name         : Visual Studio MPF 14.0
4/27/2024 3:22:33 PM - 		Version      : [14.0,17.0)
4/27/2024 3:22:33 PM - 		MoreInfoURL  : 
4/27/2024 3:22:33 PM - 		Nested       : No
4/27/2024 3:22:33 PM - 	Prerequisites      : 
4/27/2024 3:22:33 PM - 		-------------------------------------------------------
4/27/2024 3:22:33 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
4/27/2024 3:22:33 PM - 		Name         : Visual Studio core editor
4/27/2024 3:22:33 PM - 		Version      : [15.0,17.0)
4/27/2024 3:22:33 PM - Signature Details...
4/27/2024 3:22:33 PM - 	Extension is not signed.
4/27/2024 3:22:33 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by gandarez** [comment]
ARM is not fully supported by now.

https://github.com/wakatime/visualstudio-wakatime/issues/131

**Comment by princefishthrower** [comment]
Ran into the same issue... as far as I can understand in https://github.com/wakatime/visualstudio-wakatime/issues/131 there is a feature branch with arm64 that works. The only issue is that the arm64 target is missing in the CI / CD pipeline? So maybe "not planned" is a bit misleading? Or are there other issues with the arm64 build?
