### ISSUE TITLE
0 Minutes Today

### ISSUE THREAD

**Issue by PaltryProgrammer** [wakatime/visualstudio-wakatime#177]
greetings kind regards
v. 13.5.3
0 Minutes Today is being reported despite having edited for approximately one hour .
thank you kindly
![0 Minutes Today](https://github.com/user-attachments/assets/0d95eecc-115d-4f4d-a7ae-3ebe72f65e2b)

**Comment by alanhamlett** [comment]
Check your `~/.wakatime/wakatime.log` file for errors and follow this troubleshooting guide:

**Comment by alanhamlett** [comment]
Check your `~/.wakatime/wakatime.log` file for errors and follow this troubleshooting guide:
https://wakatime.com/faq#debug-plugins
