### ISSUE TITLE
Reloading solution hangs Visual Studio

### ISSUE THREAD

**Issue by slvnperron** [wakatime/visualstudio-wakatime#20]
When I switch branch (using git) on project opened in Visual Studio 2013, Wakatime makes Visual Studio hang by spawing ~20-30 python (wakatime-cli) instances.

Reproduction steps:

- Open versioned project in VS2013
- Open a few files which will differ in the new branch
- Switch branch
- In visual studio hit "Reload all"
- Open process manager and see all the python instances

**Comment by alanhamlett** [comment]
Thanks, I wonder if we can detect when VS "reloads all". If not, we can rate-limit heartbeats.

**Comment by slvnperron** [comment]
Maybe it is a DTE command (https://msdn.microsoft.com/en-us/library/envdte.commandeventsclass.aspx) but I doubt so. I think rate limiting heartbeats is the way to go since heartbeating that fast is probably always unintended?

**Comment by slvnperron** [comment]
I see that you have already rate-limited the heartbeats with the `EnoughTimePassed`. Why is it still invoking many instances?

**Comment by alanhamlett** [comment]
Enough time passed is a rate limit when editing the same file, but there is no rate limit when the file changes.

**Comment by gandarez** [comment]
@slvnperron when you say "process manager" does it mean "task manager" in windows? I'm trying to figure out this problem by following your instructions to reproduce the problem.

**Comment by alanhamlett** [comment]
I'll fix this soon. What I'll do is:

Save the last file that would have been sent, then if the rate limit is no longer being hit we can send the last edited file. This way if the user is actually switching between files quickly, their time will still be logged to the correct file.

**Comment by slvnperron** [comment]
@gandarez yes this is the windows Task Manager. I think @alanhamlett got a good solution to the problem.

**Comment by gandarez** [comment]
@slvnperron I cloned a master repo. How can I switch to branch inside Visual Studio? There's no branch loaded, only master branch.

**Comment by alanhamlett** [comment]
@gandarez Switching branches just causes a file inside the Solution to be edited outside Visual Studio... prompting the user to reload all files in the Solution. The easier way to trigger this is manually reloading all files from the menu option inside VS.

**Comment by alanhamlett** [comment]
The new `--extra-heartbeats` argument tells wakatime-cli to read from STDIN a JSON array of heartbeat data.[\[1\]][1] Now we can queue up heartbeats and send them once every few seconds[\[2\]][2] using only one python process instead of forking many python processes.

Anyone want to take a stab at this?

The JSON array should have elements of heartbeat data like the test added in [this pull request][1].

[1]: https://github.com/wakatime/wakatime/issues/45
[2]: http://www.dailycoding.com/posts/easytimer__javascript_style_settimeout_and_setinterval_in_c.aspx

**Comment by alanhamlett** [comment]
Fixed with v8.0.0.
