### ISSUE TITLE
not appear any windows to input api key after install on vs2012

### ISSUE THREAD

**Issue by programmer-1** [wakatime/visualstudio-wakatime#22]
hello,
i installed a plugin by your instruction but after restart visual studio 2012, not appear any window to input API key. this event occurred when i click on wakatime setting on tools menu too. 
thanks.

**Comment by gandarez** [comment]
Which version of VS 2012 are you using?

**Comment by programmer-1** [comment]
visual studio ultimate 2012 - version 11.0.50272.1 RTMREL

**Comment by gandarez** [comment]
I'd suggest you to redo all the steps. After uninstalling wakatime fom VS
![image](https://cloud.githubusercontent.com/assets/782854/8406794/76de1780-1e36-11e5-91cb-6e8d14f6ff47.png)
Go to users folder and delete these:
wakatime-master
.wakatime.cfg
.wakatime.db
.wakatime.log

Then try to reinstall.

**Comment by programmer-1** [comment]
I test reinstall by your instruction but not usefull. the extension installed successfully but when start visual studio not appear any window to input api key and bellow error is reported in ActivityLog.xml:

<entry>
    <record>1455</record>
    <time>2015/06/29 12:22:05.820</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [WakaTimePackage]</description>
    <guid>{52D9C3FF-C893-408E-95E4-D7484EC7FA47}</guid>
  </entry>

  <entry>
    <record>1456</record>
    <time>2015/06/29 12:22:05.820</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [WakaTimePackage]</description>
    <guid>{52D9C3FF-C893-408E-95E4-D7484EC7FA47}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>

  </entry>
  <entry>
    <record>1457</record>
    <time>2015/06/29 12:22:05.820</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [WakaTimePackage]</description>
    <guid>{52D9C3FF-C893-408E-95E4-D7484EC7FA47}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>

i think the referenced package is not related with vs2012 and i think this error occure only in vs2012.

**Comment by gandarez** [comment]
The problem occured because the plugin was referencing to Microsoft.VisualStudio.Shell.12.0. In order to have it working on VS 2012 I reverted back to Microsoft.VisualStudio.Shell.11.0
@programmer-1 Could you please try getting the version from my google drive, unpack it and run WakaTime.vsix (before running please uninstall)
https://drive.google.com/file/d/0B8xP541fEeYHaG9SaDYyRHlFcGM/view?usp=sharing

**Comment by programmer-1** [comment]
:+1:  Okay, the problem solved completely! thanks.
It should be noted that API window is displayed too late! on splash screen (About 5 minute for me)
but as a developer what was the mistake for supporting VS2012?

i thinks this issue needed to corrected as a bug fix for another version for running plugin on VS2012 properly.

thanks for your supporting.
and I apologize for my poor English. :)

**Comment by gandarez** [comment]
@programmer-1 the plugin was using a higer version of reference Microsoft.VisualStudio.Shell.

@alanhamlett I made a pull request for it. #23

**Comment by programmer-1** [comment]
thanks.
