### ISSUE TITLE
very long vs starting time with extension on

### ISSUE THREAD

**Issue by zldrq** [wakatime/visualstudio-wakatime#24]
i now have not very fast (i'm even not saying slow) internet connection and my visual studio starts like minute or so.
and when it starts in exposes no life signs, so i sometime doubt i'd ran it and run it once again for that reason. as a result have two VSs opened.

i've found that it is because it doing something in codeload.github.com. updating, likely. and i figured out, that it is this extension, that doing this.

i suppose, even on good internet connection it adds several seconds to start up time, which is no good at all.
what' more strange, it downloads something every time. i doubt that the new version comes out every few minutes..

i'm forced to switch this off, unfortunately.

if you are not planning to fix it, at least add info to description somewhere in order to not confuse users.

**Comment by gandarez** [comment]
It's a good point to be aware. Let's start analyzing which is causing this slownness.

**Comment by alanhamlett** [comment]
I found this, which I'll use to debug the slowness:
https://github.com/mschrag/speedlimit

**Comment by programmer-1** [comment]
I also have this problem, loading visual studio with this extension take about 7 minutes! On the other hand i don't think The problem to be related to the speed of the Internet because this extension load quickly with other IDE like Android Studio or phpStorm and so on.
I think this is a big technical problem that should be resolved as soon as possible up.
thanks.

**Comment by alanhamlett** [comment]
I think it's a problem detecting python, causing Python to be downloaded and installed every time you restart Visual Studio.

**Comment by programmer-1** [comment]
well, what is the solution?

**Comment by hxueh** [comment]
I have the same problem. And I am sure I did install Python 3 and set up Environment Variables correctly. Hope you solve this problem cause this is annoying.

**Comment by alanhamlett** [comment]
I've relaxed the python detection slightly and increased logging in the current version 5.0.5. Can you update the WakaTime plugin.

Also make sure to turn on debug mode from WakaTime -> Settings inside VS, then re-launch VS from command line with `devevn /log` ([more info](http://blogs.msdn.com/b/visualstudio/archive/2010/02/24/troubleshooting-with-the-activity-log.aspx)).

With the new logging, we should see which step is taking up so much time while starting.

**Comment by programmer-1** [comment]
The problem has been solved properly. thanks.

As others have pointed out, The problem must be from the Detecting Python.
this is related WakaTime records in my vs log file after updating WakaTime and running vs in a log mode:

<entry>
    <record>941</record>
    <time>2015/07/18 05:25:35.720</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Importing pkgdef file</description>
    <path>[User Directory]\AppData\Local\Microsoft\VisualStudio\11.0\Extensions\3u4cgngf.uws\WakaTime.pkgdef</path>
</entry>

<entry>
    <record>1273</record>
    <time>2015/07/18 05:25:40.676</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [WakaTimePackage]</description>
    <guid>{52D9C3FF-C893-408E-95E4-D7484EC7FA47}</guid>
</entry>

<entry>
    <record>1276</record>
    <time>2015/07/18 05:25:40.692</time>
    <type>Information</type>
    <source>WakaTime.Logger</source>
    <description>Initializing WakaTime v5.0.5</description>
</entry>

<entry>
    <record>1277</record>
    <time>2015/07/18 05:25:40.692</time>
    <type>Information</type>
    <source>WakaTime.Logger</source>
    <description>Found python via registry at: C:\Python34\pythonw</description>
</entry>

<entry>
    <record>1278</record>
    <time>2015/07/18 05:25:41.022</time>
    <type>Information</type>
    <source>WakaTime.Logger</source>
    <description>Finished initializing WakaTime v5.0.5</description>
</entry>

<entry>
    <record>1279</record>
    <time>2015/07/18 05:25:41.022</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [WakaTimePackage]</description>
    <guid>{52D9C3FF-C893-408E-95E4-D7484EC7FA47}</guid>
</entry>

thanks again for sloving problem.

**Comment by alanhamlett** [comment]
Awesome!
