### ISSUE TITLE
why not use output view instead of ActivityLog.xml for user-friendly

### ISSUE THREAD

**Issue by yyjdelete** [wakatime/visualstudio-wakatime#30]
As [CodeMaid](https://github.com/codecadwallader/codemaid/blob/cfc386ff725c73f11db8a0bf21cd55bd62d91ebe/CodeMaid/Helpers/OutputWindowHelper.cs) does.

**Comment by alanhamlett** [comment]
Great idea, I always disliked ActivityLog.xml but didn't know an alternative. I'll get this changed soon.

**Comment by alanhamlett** [comment]
Implemented with #31.
