### ISSUE TITLE
Waketime does not work on all network

### ISSUE THREAD

**Issue by Praxkv1** [wakatime/visualstudio-wakatime#36]
I have wake time installed as a plugin to my Visual studio 2012. I see that it logs my activity only when I am connected to internet from home. It does not logs anything when I connected via office internet.

**Comment by gandarez** [comment]
When at office do you need proxy authentication?

**Comment by Praxkv1** [comment]
We use citrix to connect to office network. Its automatically gets connected when we login to our laptop in office.

**Comment by gandarez** [comment]
Do you have the latest version installed (5.0.7)? 
Go to Tools -> Wakatime -> Settings and enable Debugging. After show us the Output window like below
![image](https://cloud.githubusercontent.com/assets/782854/8941594/d1d8aa5c-3546-11e5-9c1b-49aa9340e16b.png)

**Comment by alanhamlett** [comment]
@Praxkv1 currently you have to manually configure the proxy in the WakaTime settings menu. Can you find the proxy that Citrix uses after it connects?

**Comment by l7l1l0l** [comment]
When I input the wakatime  API key, an error "object reference not set to an instance of an object".I want to know how to solve this problem.
Visual stdio 2012  Windows7

**Comment by Praxkv1** [comment]
@alanhamlett  Thanks for the update. I found a option to enter the proxy address in VS2012 under Tools-->WakaTime-->Setting--Proxy.
Can you please help me how to find what proxy my computer is using. I tried all the options available in  Citrix setting but i could not find any thing.

**Comment by alanhamlett** [comment]
@l7l1l0l the latest version of the plugin (v5.0.8) should fix the api key bug.

**Comment by alanhamlett** [comment]
@Praxkv1 I think the easiest way is open your browser and go to the proxy settings, then copy the host and port used.
