### ISSUE TITLE
Visual Studio 2012 + Windows7 input API key, object reference not set to an instance of an object

### ISSUE THREAD

**Issue by l7l1l0l** [wakatime/visualstudio-wakatime#37]
When I input API key, the error is "object reference not set to an instance of an object"

**Comment by gandarez** [comment]
PR #38

**Comment by l7l1l0l** [comment]
Thank you very much.

**Comment by l7l1l0l** [comment]
I download wakatime plugin from Visual Studio, error again. I don't know how to use v5.0.8's code.

**Comment by gandarez** [comment]
@l7l1l0l version 5.0.8 isn't released yet.
https://visualstudiogallery.msdn.microsoft.com/ca0ea1f3-e824-4586-a73e-c8e4a65323d8

**Comment by alanhamlett** [comment]
Just released v5.0.8.

**Comment by l7l1l0l** [comment]
I download v5.0.8 in my Visual Studio, The error is not appear again. But it didn't seem to work properly,because wakatime DashBoard no data. How can I be sure wakatime client send data to wakatime server?

**Comment by alanhamlett** [comment]
First, take a look at this [troubleshooting guide](https://github.com/wakatime/wakatime#troubleshooting) to look for error messages in your ~/.wakatime.log file.

**Comment by yyjdelete** [comment]
Maybe relate to #33 , seems @l7l1l0l is an Chinese.
