### ISSUE TITLE
Support for Visual Studio 2015

### ISSUE THREAD

**Issue by kidchenko** [wakatime/visualstudio-wakatime#4]
:+1:

**Comment by arpadszasz** [comment]
There is a quick workaround for this:

1. download the [WakaTime extension](https://visualstudiogallery.msdn.microsoft.com/ca0ea1f3-e824-4586-a73e-c8e4a65323d8) for VisualStudio
2. open the extension file `WakaTime.vsix` using [7-Zip File Manager](http://www.7-zip.org/) (it's just a ZIP archive)
3. edit the file `extension.vsixmanifest` changing all occurances of `InstallationTarget` like this: `<InstallationTarget Version="[14.0]"`
4. save the modified extension
5. double-click on the extension file to install it in VisualStudio 2015

**Comment by kiide** [comment]
i can make an PR? haha

**Comment by arpadszasz** [comment]
Using this hack, it installs on VS2015, but it does not send any data to WakaTime. So we'll have to wait for a official port. :smile:

**Comment by alanhamlett** [comment]
That must mean it installs but doesn't run.

**Comment by kiide** [comment]
:(

**Comment by kiide** [comment]
@alanhamlett you has python?

**Comment by kiide** [comment]
If I work in the official plugin and make a PR, you accept? (wakatime)

**Comment by arpadszasz** [comment]
I had VS2013 with the WakaTime extension previously running on the same machine, before I switched to VS2015.

Today I uninstalled Python, the WakaTime extension from VS2015 and cleaned up all WakaTime related files from my home folder, reinstalled the modified extension again in VS2015. It installed Python and asked for the WakaTime API key on first run but it does not send any data to WakaTime servers. Also it asks for the API key on every start of VS2015.

**Comment by kiide** [comment]
I will check it.

**Comment by alanhamlett** [comment]
Support for Visual Studio 2015 was added with #7

**Comment by kidchenko** [comment]
Thanks!
