### ISSUE TITLE
give user option to cancel python download/install

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/visualstudio-wakatime#40]

**Comment by gandarez** [comment]
When initializing? Give me more details.

**Comment by yyjdelete** [comment]
Why download wakatime-cli.zip blocking the startup of VS(showing the LOGO) instead of download in background/async?

**Comment by gandarez** [comment]
It's a new way of initializing wakatime

**Comment by alanhamlett** [comment]
We should download in the background, but prompt the user in the UI thread before downloading just in case the user does not want Python installed for some reason.

**Comment by gandarez** [comment]
@alanhamlett Might we give to the user ability to add its own python's directory?

**Comment by alanhamlett** [comment]
Fixed with #45
