### ISSUE TITLE
Wakatime doesn't work on my visual studio2012.

### ISSUE THREAD

**Issue by l7l1l0l** [wakatime/visualstudio-wakatime#44]
#37 It doesn't work again.
I remove all wakatime files in my computer. Install wakatime again, after restart, Have no place to enter API key.
Moreover, Notepad++,Vim,Sublime text3 cannot waketime normal running. There are many errors in vim about python. Even if I have update the 2.7.9 python.

**Comment by gandarez** [comment]
@l7l1l0l o you see this menu?
![image](https://cloud.githubusercontent.com/assets/782854/9578270/c4734b5a-4fbe-11e5-9991-705cc47260d5.png)

**Comment by l7l1l0l** [comment]
wakatime for Visual Stdio is ok. Thank you very much.
