### ISSUE TITLE
Python appears called for every file, and stays in memory

### ISSUE THREAD

**Issue by hugodahl** [wakatime/visualstudio-wakatime#46]
I was diagnosing some issues on my project in Process Explorer, when I noticed a good number of "pythonw.exe" processes running. The command lines are pretty much all the same, except for the "file" argument. Even after closing the files from within Visual Studio, the processes remained. I then quit Visual Studio (single instance this time), and the processes remain.

I've attached 2 screenshots of Process Explorer, showing the process tree. It can be seen when VS is running, that there are child processes to it. There were also already "orphan" processes. After exiting VS, more orphan processes are left behind.

With Visual Studio still running, processes children of devenv.exe
![VS Running](https://cloud.githubusercontent.com/assets/757374/9859500/872f3fea-5aec-11e5-88a5-844d68e40c82.png)

After exiting Visual Studio, processes running, but orphaned
![VS Exited](https://cloud.githubusercontent.com/assets/757374/9859518/9f4f6848-5aec-11e5-9501-8b2062e55234.png)

**Comment by gandarez** [comment]
@hugodahl great point. I'll do some tests tonight.

**Comment by alanhamlett** [comment]
@hugodahl one possible explanation is network connectivity. Each `pythonw.exe` process is [wakatime cli](https://github.com/wakatime/wakatime) sending a heartbeat to the api. I've updated the default timeout of wakatime cli to 30 seconds in the latest release, so re-launching Visual Studio will download the new wakatime cli and might fix this for you...

**Comment by gandarez** [comment]
@hugodahl Did you test as @alanhamlett said?

**Comment by alanhamlett** [comment]
@hugodahl does data from your Visual Studio on this particular machine show up on the dashboard?

**Comment by alanhamlett** [comment]
Fixed with v8.0.0.
