### ISSUE TITLE
Prompt to install Python appears behind VS window

### ISSUE THREAD

**Issue by arangas** [wakatime/visualstudio-wakatime#48]
I just did a clean install of VS 2015 and installed Wakatime 6.0.0. After the restart required by installing the extension, nothing appeared to have happened. Looking closer, I could see that there was a second VS window hidden behind the main window - the dialog that prompts to download and install Python. It would be nice to have this in the foreground after the VS restart.

**Comment by Leon-O** [comment]
Uninstall that version and re-install it from visual studio galley

**Comment by gandarez** [comment]
@arangas please refer to my forked repo in https://github.com/gandarez/visualstudio-wakatime
I excluded the verification of python installation from async task and it should appear earlier than the main screen.

**Comment by arangas** [comment]
@Leon-O I thought that was the same as installing through VS? In any case, I get the same result.

@gandarez Thanks I would like to but due to time constraints I will workaround this by installing Python manually as suggested in #49.

**Comment by gandarez** [comment]
@arangas it should be the same as installing through VS.
