### ISSUE TITLE
Unable to install Python through dialog prompt

### ISSUE THREAD

**Issue by arangas** [wakatime/visualstudio-wakatime#49]
I just did a clean install of VS 2015 and installed Wakatime 6.0.0 on Windows 10. After clicking "Yes" on the prompt to install Python, nothing appeared to happen for about 10 seconds. Then a window flashed briefly on the screen, followed by a Windows Installer error "This installation package could not be opened. Verify that the package exists and that you can access it, or contact the application vendor to verify that this is a valid Windows Installer package."

**Comment by Leon-O** [comment]
i had the same problem, just go to https://www.python.org/, download the installer according your system and them run your VS 2015

**Comment by gandarez** [comment]
@arangas the installer has around 25mb, depends on your local connection you could wait longer than usually. The file python.msi goes to c:\users\{user}. Alternatively you can download it manually as @Leon-O said.

**Comment by arangas** [comment]
Hmmm the dialog doesn't state which version (2.x or 3.x). Does this matter?

**Comment by gandarez** [comment]
@arangas Wakatime is current on version 6.0.0

@alanhamlett please increment version number and upload it to the gallery
