### ISSUE TITLE
VS 2015 in Parallels VM Freezing

### ISSUE THREAD

**Issue by mtrutledge** [wakatime/visualstudio-wakatime#51]
When I use WakaTime plugin with Visual Studio 2015 Enterprise inside a Parallels 11 VM it will freeze Visual Studio. I haven't quite determined the exact steps to reproduce this. It consistently happens after the computer goes to sleep. It will also happen if I don't focus on the Visual Studio window for a while. I thought that maybe it was my VM. So I installed visual studio from scratch and worked with it and had no problems. As soon as I installed the WakaTime plugin through the extensions manager the problem occurred again.

**Comment by gandarez** [comment]
@mtrutledge Since Parallels is a VM and emulates windows on MAC I'm not able to answer you what's happening.

**Comment by alanhamlett** [comment]
I have Virtual Box, but not Parallels. Can you run Visual Studio from command line with `devenv /log` then check your ActivityLog.xml file for WakaTime errors?

(http://blogs.msdn.com/b/visualstudio/archive/2010/02/24/troubleshooting-with-the-activity-log.aspx)

**Comment by MZetko** [comment]
Hello there, the exact same thing happens to me on my PC, even without Vritual Box o Parallels. I have been seeking which plugin is causing this and it seems Wakatime is the source. The issue happens when VS is inactive for a while. After I want to go back to VS, it is just unresponsive, looks "frozen", without any loading cursor or anything. I just doesn't capture any input. Also, when multiple instances of VS are open, they all freeze. Only way to get rid of them is to kill their processes one by one.

**Comment by shivamadhavan** [comment]
The same observed with VS2013 as well. No entries(/errors) in ActivityLog.xml related to WakaTime other than these;
```
  <entry>
    <record>229</record>
    <time>TIME_STAMP_HERE</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [WakaTimePackage]</description>
    <guid>{52D9C3FF-C893-408E-95E4-D7484EC7FA47}</guid>
  </entry>
<entry>
    <record>230</record>
    <time>TIME_STAMP_HERE</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [WakaTimePackage]</description>
    <guid>{52D9C3FF-C893-408E-95E4-D7484EC7FA47}</guid>
  </entry>
```

**Comment by ssarabando** [comment]
Same observed with Visual Studio 2015 Professional (14.0.24720.00 Update 1). Nothing of note in the ActivityLog either. What can I do to help hunting down this bugger, since it's keeping me from using Wakatime in VS (works fine with Sublime).

**Comment by JeroenVandezande** [comment]
I have the same issue, it only freezes one VS, other instances do not necessary freeze at the same time.
I use VS2015 Community edition. WakaTime works fine in Suble edit without any freezing on the same computer.
I disabled the plug-in but I would like to find a solution for this though. (I am a paying customer of WakaTime and 80% of my work is in VS)

Best Regards,

Jeroen

**Comment by alanhamlett** [comment]
Could this be related to #20 or does it crash anytime you edit/save a single file?

**Comment by JeroenVandezande** [comment]
No it does not crash when I am just editing code, it is more when I do edit code and then read something on a pdf or website for a couple of minutes, when I come back VS is completely frozen. 
But not in a way that Task Manager detects it (like "not responding"), no it seems like it just ignores keyboard and mouse commands.

**Comment by plfoley** [comment]
I discovered I can make it happen on demand when changing the Visual theme (Light/Dark/Blue) in the VS 2015 options. Had to uninstall, VS became unusable with this extension.

**Comment by ricardopolo** [comment]
:+1:

**Comment by loubouchet** [comment]
Exactly the same issue here. Was pulling my hair out. Thanks for the info guys. Disabling Wakatime for now...

**Comment by jaydeepkarena** [comment]
Same issue here, I am using Visual Studio 2015 Community on Windows7 and even after uninstalling WakaTime, i can't debug my application, It just freezes at any breakpoint. I have to kill vs then re-open it.

**Comment by jakubsuchybio** [comment]
Reported this to VS guys. Year later with year of freezing I found that it might be doing wakatime... So here we are. MSFT responded they will not fix this. It is some sort of Finalizer Threadlock most probably. I'm just finding it really unprofessional to have this kind of bug in production in extensibility APIs. Anyway, here is a full details. https://developercommunity.visualstudio.com/content/problem/135843/visual-studio-frozen-randomly.html

**Comment by alanhamlett** [comment]
@jakubsuchybio are you using VS inside a virtual machine? If you're not using a virtual machine then let's open a new issue since this one seems to only happen when using inside a VM.
