### ISSUE TITLE
offline / sync does not always work

### ISSUE THREAD

**Issue by rs38** [wakatime/visualstudio-wakatime#55]
visual studio 2015 community

Is there a way to trace the plug or easily access the wakatime.db?
I guess if the date stamp of the .db file is later than  last work there is probably nothing to sync?

**Comment by alanhamlett** [comment]
You can [turn on debugging](https://github.com/wakatime/wakatime#configuring) in your `~/.wakatime.cfg` file, then tail `~/.wakatime.log` to see coding activity as it is recorded.

To view the backlog of heartbeats run:

```
$ sqlite3 ~/.wakatime.db
sqlite> select * from heartbeat_1;
sqlite> .quit
```

If there's a problem with the plugin, then the heartbeats might not be saved to the local sqlite db when offline. There would be evidence of that in your `~/.wakatime.log` file unless the plugin crashed. In that case you should check your Output Window in VS and your [ActivityLog.xml](http://blogs.msdn.com/b/visualstudio/archive/2010/02/24/troubleshooting-with-the-activity-log.aspx).

**Comment by rs38** [comment]
thank you! I already activated both loggings, will check during the coming day.
can you please explain a bit more in which shell you connect to the sqlite3 db? I get syntax errors if I try that with python.exe shell with it's `>>>` prompt.

**Comment by alanhamlett** [comment]
I'm not sure how to open sqlite files in Windows, that command was for Bash in Linux.

**Comment by alanhamlett** [comment]
Any updates from this?

**Comment by rs38** [comment]
I finally could open the database but it was empty.
Can be closed.
