### ISSUE TITLE
Doesn't ask for api key on VS 2015 Enterprise, setting don't show

### ISSUE THREAD

**Issue by daronjay** [wakatime/visualstudio-wakatime#56]
Getting this message in output, and nothing else ever happens. Wakatime Settings won't open.

[Wakatime Info 10:55:17 AM] Initializing WakaTime v7.0.2
[Wakatime Info 10:55:18 AM] Current wakatime-cli version is 4.1.13
[Wakatime Info 10:55:18 AM] Checking for updates to wakatime-cli...
[Wakatime Warning 10:55:19 AM] Couldn't auto resolve wakatime cli version
[Wakatime Info 10:55:19 AM] Found an updated wakatime-cli v

**Comment by gandarez** [comment]
It's seems not to be a real problem. Have you previously installed in this machine Waka?

**Comment by daronjay** [comment]
No, just tried to install / uninstall twice, got same problem and no Api key request. Also no way to open settings for wakatime, the tools> wakatime > settings menu command does nothing at all

**Comment by daronjay** [comment]
Actually, it seems to summon up a dialogue, but it was hidden behind window

**Comment by alanhamlett** [comment]
So we need to find a way to make sure the dialog window is in the front and focused.

**Comment by daronjay** [comment]
I'm in, the dialog was hidden behind window and didn't appear for a while. That's for your prompt reply!

**Comment by daronjay** [comment]
I reckon, especially if app is full screen

**Comment by daronjay** [comment]
Maybe add a text  to the console output when the dialogue window is launched, because it seemed to take a few minutes, and you could say it might be behind the window and that they need to add their key

**Comment by alanhamlett** [comment]
b8b823b3c3e1ad916dd1e2a0bdfe4b72c9f75f7d should fix this.

**Comment by gandarez** [comment]
@alanhamlett it happens because we changed the loading process to be async, remember?
