### ISSUE TITLE
Wakatime freezes visual studio 2013

### ISSUE THREAD

**Issue by jjkalafut** [wakatime/visualstudio-wakatime#59]
I'm having two issues, which may or may not be related.

1) I have a code project that builds a DLL and then launches an outside exe to run and load the DLL. For this solution in particular (does not happen in all my solutions) whenever i try to localy debug my code, as soon as the external exe starts to run (has not loaded my DLL yet) visual studio freezes and will not respond, even if i close the launched program. As soon as I disable wakatime, it no longer freezes. 

2)Occasionally, if i have  multiple solutions open, one of them will freeze in the same manner suggested above; the program will not respond to any command and must be force closed and restarted.

**Comment by gandarez** [comment]
Could you share your solution?
I'm using VS 2013 and 2015 with no problems of freezing.

**Comment by jjkalafut** [comment]
Unfortunately I can't share the code (for a few reasons). If there is any system information or logs that would help, I could share those however.

**Comment by gandarez** [comment]
You could share the ActivityLog.xml
```
%APPDATA%\Microsoft\VisualStudio\12.0\ActivityLog.xml
```

**Comment by jjkalafut** [comment]
I re-enabled wakatime to try and get a log of the problem, but now it seems to be playing nicely. I will update if the problem arises again.

**Comment by gandarez** [comment]
Ok ping me if needed.
