### ISSUE TITLE
Support for Visual Studio 2010

### ISSUE THREAD

**Issue by MatiasL13** [wakatime/visualstudio-wakatime#6]
there any way to install it in Visual Studio 2010?

**Comment by alanhamlett** [comment]
Not yet, but we do plan to support VS2010. I'll update here when it's ready.

**Comment by matthewseng** [comment]
Would be great to have, I'm stuck with VS2010 :(

**Comment by gandarez** [comment]
I'll try tomorrow to have it working on vs 2010.

**Comment by J-kit** [comment]
I need this plugin for vs2010 ;(

**Comment by alanhamlett** [comment]
Fixed with 2b593f704fcff1f7fff12a42c1b68285538c3860.
