### ISSUE TITLE
no way to Enter API key

### ISSUE THREAD

**Issue by xs020105** [wakatime/visualstudio-wakatime#60]
![qq 20160803230958](https://cloud.githubusercontent.com/assets/13690881/17370671/7ff38c8a-59cf-11e6-8684-9e14165edc36.png)
there is no api key put in when i restart Visual Studio,and its always Initializing.how can i deal it

**Comment by alanhamlett** [comment]
Your api key can be found from Tools -> WakaTime Settings.
