### ISSUE TITLE
Visual Studio 2017 RC support

### ISSUE THREAD

**Issue by piwnik** [wakatime/visualstudio-wakatime#61]
Please support Visual Studio 2017 RC.

**Comment by gandarez** [comment]
I think would be better to wait a final version.

**Comment by alanhamlett** [comment]
I've been looking into VS 2017 support but the vsix built with Visual Studio 2017 RC gives this error when uploading to the Marketplace:

`This extension targets Visual Studio 2017 but was not built with an up-to-date VSSDK. Please make sure to update your references and try uploading again. Note: you'll also need to add Prerequisites to your extension.vsixmanifest.`

Hopefully I'll figure it out soon.

**Comment by alanhamlett** [comment]
Looks like we have to create a new extension for 2010 support and use the v3 manifest file for this extension to support VS 2017...

**Comment by alanhamlett** [comment]
@piwnik try installing from the Gallery (inside Visual Studio) and let me know if v8.0.5 works with VS2017 RC.

**Comment by alanhamlett** [comment]
Now supports 2017:
https://marketplace.visualstudio.com/items?itemName=WakaTime.WakaTime
