### ISSUE TITLE
Visual Studio 2017 extension is not logging or reporting time

### ISSUE THREAD

**Issue by nckl** [wakatime/visualstudio-wakatime#69]
I am unable to get WakaTime extension for VS 2017 to log or report time. I have also installed the extension for VS Code and that is working correctly.

The  extension has installed correctly (or so it appears). 
The output window for WakaTime does not indicate that there is anything wrong.
The API key has been added and it shown in the wakatime.cfg file
In the wakatime.log file there are entries for VS Code but not for Visual Studio.
ActivityLog.xml also does not indicate anything is wrong.

Any other suggestions on what i should be looking at to fix?

Thanks,

**Comment by alanhamlett** [comment]
Is there a File/Tools -> WakaTime Settings menu in VS?

**Comment by nckl** [comment]
Yes the menu option is present.
Api key contains the Api key in my account.
There is no proxy set
And debugging is enabled.

Thanks.

**Comment by nckl** [comment]
One thing to note. I uninstalled the Visual Studio plug and remove the three wakatime files from the profile directory. When I reinstalled wakatime only the config file is able to be created there is no log file created. FWIW i am running VS 2017 v15.4.1

lastly when uninstalling wakatime it does not clean up the wakatime directory in appdata\roaming.

Hopefully you find this useful. Since i was unable to get this working for me I have had to uninstall completely.

Thanks.

**Comment by JayPeet** [comment]
I had the same issue today.

Fixed it by reinstalling python 2.7. I did have python installed when it did work, but then was required to reset my Windows install, which caused python to stop working.

Hope that helps anyone else with the issue.
