### ISSUE TITLE
Visual Studio Window API Key is very small on high definition screen

### ISSUE THREAD

**Issue by nicolasroux** [wakatime/visualstudio-wakatime#70]
Hi, 

I just installed the plugin... here is a screen capture of the window to fill my licence key:

![vs_caption](https://user-images.githubusercontent.com/7628019/31895083-8c3ab658-b810-11e7-98b8-ad29b593ede6.png)

My resolution screen is 3840x2160 and The window is very tiny...

**Comment by alanhamlett** [comment]
This is an issue with Vscode's Extension API, since it doesn't allow changing the size of [input boxes](https://code.visualstudio.com/docs/extensionAPI/vscode-api#InputBoxOptions).

**Comment by nicolasroux** [comment]
Are you sure it has todo with VSCode ? this is running on Visual Studio Community, not VSCode. 

And by the way, the whole window is tiny, maybe make it resizable would be an option.

**Comment by alanhamlett** [comment]
Oops, sorry I thought this was Vscode. For Visual Studio we can make this window larger.

**Comment by gandarez** [comment]
Fixed on version 9.0.1
