### ISSUE TITLE
Why two instances in the marketplace VS2017 community

### ISSUE THREAD

**Issue by CaddyDz** [wakatime/visualstudio-wakatime#71]
There are two instances of the Wakatime extension in the Visual Studio Extensions and Updates window as the screenshot below displays, why is that? and which one should I install?
![capture](https://user-images.githubusercontent.com/13698160/34468173-24529888-eeb8-11e7-923f-8d6cfefcb3b5.PNG)

**Comment by alanhamlett** [comment]
One should be called `WakaTime (2010)` and the other just `WakaTime`:
https://marketplace.visualstudio.com/search?term=wakatime&target=VS

If you're using Visual Studio 2010 then you want the legacy 2010 version, otherwise you want the normal WakaTime version.

**Comment by CaddyDz** [comment]
Thanks for the explanation
