### ISSUE TITLE
Problem installing Plugin for Visual Studio 2010

### ISSUE THREAD

**Issue by NunzioModesto** [wakatime/visualstudio-wakatime#73]
Hi I have problems installing the plugin in VS2010 .
I installed the plugin following the instructions where VS restarts it reports an error
I started VS2010 with the /log option and checked the activitylog.xml file
I noticed that the plugin can't start because it's looking for Microsoft.VisualStudio.Shell.11.0 which apparently is missing.

Any help would be aprriciated

**Comment by NunzioModesto** [comment]
Solved!
I copied the missing assempby Microsoft.VisualStudio.Shell.11.0 from another machine where there is a VS2012 installed and copied to the same folder of the WakaTime dll

Would be nice to update the distribution package to include that file to avoid problems on machines where there is only a VS2010 installed.

**Comment by wrb233** [comment]
thank you for your experience！！！
