### ISSUE TITLE
APi's settings

### ISSUE THREAD

**Issue by khixr111** [wakatime/visualstudio-wakatime#79]
where are the API's settings in VS 2015

**Comment by alanhamlett** [comment]
Settings for the VS plugin are inside Visual Studio's built-in menu:

Tools -> WakaTime Settings

Settings for the [WakaTime core](https://github.com/wakatime/wakatime#configuring) are stored in an INI file at `C:\Users\<user>\.wakatime.cfg`.

More info about settings and troubleshooting:
https://github.com/wakatime/visualstudio-wakatime#troubleshooting
