### ISSUE TITLE
Support for Visual Studio 2013

### ISSUE THREAD

**Issue by jonhider** [wakatime/visualstudio-wakatime#8]
Been trying to get this to work for a couple of weeks now on Visual Studio 2013 Ultimate and it's still not working.  Currently running the 3.0 plugin which has been uninstalled/re-installed and still not seeing it working.  .wakatime.log, .wakatime.db, .wakatime.cfg files are reside in C:\Users\"username" directory and log file is blank.  .wakatime.cfg just shows my API key.  Would like to really look deeper into using this plugin, but need assistance.  Thanks.

**Comment by alanhamlett** [comment]
Can you look for any WakaTime related messages in your ActivityLog.xml file?

https://msdn.microsoft.com/en-us/library/bb166359.aspx

**Comment by jonhider** [comment]
Nothing in there related to wakatime

**Comment by alanhamlett** [comment]
The VS Ultimate SKU was missing in the build, but it's been added in v4.0.1 so should work now.
