### ISSUE TITLE
Support for Visual Studio 2019 

### ISSUE THREAD

**Issue by pocki** [wakatime/visualstudio-wakatime#83]
Support for Visual Studio 2019 (Preview) would be nice. 
Mabye this can be helpful [https://blogs.msdn.microsoft.com/visualstudio/2018/09/26/how-to-upgrade-extensions-to-support-visual-studio-2019/](https://blogs.msdn.microsoft.com/visualstudio/2018/09/26/how-to-upgrade-extensions-to-support-visual-studio-2019/)

**Comment by draniza355** [comment]
https://blogs.msdn.microsoft.com/visualstudio/2018/09/26/how-to-upgrade-extensions-to-support-visual-studio-2019/
#84 Upgrade to VS 2019

**Comment by alanhamlett** [comment]
Implemented with #84
