### ISSUE TITLE
Support BackwardsCompatibleAsyncPackage

### ISSUE THREAD

**Issue by gandarez** [wakatime/visualstudio-wakatime#87]
https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-asyncpackage-to-load-vspackages-in-the-background?view=vs-2019

**Comment by alanhamlett** [comment]
Also an example:

https://github.com/Microsoft/VSSDK-Extensibility-Samples/blob/master/Backwards_Compatible_AsyncPackage_2013/BackwardsCompatibleAsyncPackage/BackwardsCompatibleAsyncPackage.cs

**Comment by gandarez** [comment]
There's no more deprecated api warning :)

PR made at https://github.com/wakatime/visualstudio-wakatime/pull/90

![image](https://user-images.githubusercontent.com/782854/55671039-e515e480-5861-11e9-8674-131d812404fe.png)
