### ISSUE TITLE
Installing instruction can be wrong

### ISSUE THREAD

**Issue by urbanmichal** [wakatime/visualstudio-wakatime#93]
Installing instructions (https://wakatime.com/visual-studio) states:

"Inside Visual Studio, navigate to Tools → Extensions and Updates…"

In VS 2019 (16.0.3, stable version) there's no "Extensions and Updates..." menu item, but Extensions menu after Tools menu.

**Comment by alanhamlett** [comment]
Updated the instructions, will update screenshot also in future.
